### ISSUE TITLE
Tabs In fullscreen are not full width anymore

### ISSUE THREAD

**Issue by acondiff** [mdo/hyperterm-atom-dark#15]
There is still margin left for the traffic lights on the tabs container when Hyper is in fullscreen. Traffic lights are not displayed so it is just an empty gap. Margin should return when menubar is evoked by mousing to the top of your screen.

**Comment by iamstarkov** [comment]
its not a problem with a theme

**Comment by iamstarkov** [comment]
its the hyper's issue

**Comment by iamstarkov** [comment]
im considering to close this issue

**Comment by acondiff** [comment]
Oh, you are right, this issue happens regardless of the theme I use. My apologies.

**Comment by iamstarkov** [comment]
mind closing issue here, and open it in hyper repo?

**Comment by acondiff** [comment]
I opened an issue on Hyper. Sorry for the confusion.

**Comment by iamstarkov** [comment]
no worries, have fun on a weekend
