### ISSUE TITLE
No visible split pane identifier

### ISSUE THREAD

**Issue by jwandrews** [mdo/hyperterm-atom-dark#9]
With the release of split panes in Hyper, it would nice to have an visual line to show the panes in the open tab / window.

Currently is it set to the same color as the background which can be a pain to quickly identify the separate panes that are open.

I can submit a PR for review if needed.

**Comment by iamstarkov** [comment]
i think PR is needed, we did the same for hyper-one-light https://github.com/andrepolischuk/hyper-one-light/issues/8

**Comment by gamebox** [comment]
Would love to see this merged.  But I am but one man.

**Comment by jrdnbwmn** [comment]
This doesn't appear to be working anymore—I'm not seeing the line anymore. I _do_ still see it on https://github.com/andrepolischuk/hyper-one-light/issues/8.
